// sidebars.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Main Docs sidebar (shared docs experience)
  mainDocsSidebar: [
    {
      type: "category",
      label: "GETTING STARTED",
      className: "sidebar-section",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },
    {
      type: "category",
      label: "ADMINISTRATION",
      className: "sidebar-section",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "administration",
        },
      ],
    },
    {
      type: "category",
      label: "AUTONOMOUS AGENTS",
      className: "sidebar-section",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "autonomous-agents",
        },
      ],
    },
  ],

  // Voice & Headless Agents sidebar
  cibaSidebar: [
    {
      type: "autogenerated",
      dirName: "ciba",
    },
  ],

  // SDK sidebar
  sdkSidebar: [
    {
      type: "autogenerated",
      dirName: "sdk",
    },
  ],

  // Status sidebar
  statusSidebar: [
    {
      type: "autogenerated",
      dirName: "status",
    },
  ],
};

module.exports = sidebars;
